stages:
  - lint
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

lint: 
  image: node:lts
  stage: lint
  before-script:
    - npm install
  script:
    - npm run lint

# unit-test:
#   image: node:lts
#   stage: test
#   script:
#     - npm run test:unit

# e2e-test:
#   image: node:lts
#   stage: test
#   script:
#     - npm run test:e2e

build:
  image: node:lts
  stage: build
  script: 
    - npm run build
  # only:
  #   - master

deploy:
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:0.0.1" .
    - docker push "$CI_REGISTRY_IMAGE:0.0.1"
  # only:
  #   - master
