stages:
  - lint
  - deploy

cache:
  paths:
    - node_modules/

test:
  image: node:lts
  stage: test
  script:
    - npm install
    - npm run test
#     - npm run test:e2e
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour


# --- 아래 1.0.0 배포 후 설정 ---

# build:
#   image: node:lts
#   stage: build
#   script: 
#     - npm run build
#   artifacts:
#     paths:
#       - dist/
#     expire_in: 1 hour
#   # only:
#   #   - master

# deploy:
#   stage: deploy
#   image: docker:stable
#   services:
#     - docker:dind
#   before_script:
#     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
#   script:
#     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#     - docker push "$CI_REGISTRY_IMAGE"
#   # only:
#   #   - master
