image: node:lts

stages:
  - install
  - lint
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint: 
  stage: lint
  script:
    - npm run lint

# unit-test:
#   stage: test
#   script:
#     - npm run test:unit
  # cache:
  #   key: ${CI_COMMIT_REF_SLUG}
  #   paths:
  #     - node_modules/
  #   policy: pull

# e2e-test:
#   stage: test
#   script:
#     - npm run test:e2e
  # cache:
  #   key: ${CI_COMMIT_REF_SLUG}
  #   paths:
  #     - node_modules/
  #   policy: pull

build:
  stage: build
  script: 
    - npm run build
  # only:
  #   - master

deploy:
  stage: deploy
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:0.0.1" .
    - docker push "$CI_REGISTRY_IMAGE:0.0.1"
  # only:
  #   - master
