image: node:lts

stages:
  - lint
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

lint: 
  stage: lint
  script:
    - npm install
    - npm run lint
  cache:
    paths:
      - node_modules/


# unit-test:
#   stage: test
#   script:
#     - npm run test:unit
  # cache:
  #   key: ${CI_COMMIT_REF_SLUG}
  #   paths:
  #     - node_modules/

# e2e-test:
#   stage: test
#   script:
#     - npm run test:e2e
  # cache:
  #   key: ${CI_COMMIT_REF_SLUG}
  #   paths:
  #     - node_modules/

build:
  stage: build
  script: 
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  # only:
  #   - master

deploy:
  services:
    - docker:19.03.12-dind
  image: docker:19.03.12
  stage: deploy
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:0.0.1" .
    - docker push "$CI_REGISTRY_IMAGE:0.0.1"
  # only:
  #   - master
